### ISSUE TITLE
Question about multi-animal dannce, follow-up to #103

### ISSUE THREAD

**Issue by shwan19** [spoonsso/dannce#115]
Hi DANNCE team,

I work with kdquine who posted in #103 regarding multi-animal DANNCE. So far, we have tried your advice of treating the two animals in our assay (let's call them A and B) as independent instances for the purpose of DANNCE training. We trained the DANNCE network by separately listing under the `exp:` block the COM/DANNCE label files for animal A and the COM/DANNCE label files for animal B. Please see io.yaml code below.

We also noticed that the top-level `com_file:` at the very bottom of io.yaml could not be left empty and could not hold two COM files simultaneously, so we arbitrarily picked a single COM file to list here during dannce-train. During one-animal-at-a-time dannce-predict, it seems that the DANNCE predictions generally correspond to the animal whose COMs are listed until the top-level `com_file:`.

Here are our questions:

1) Does the top-level `com_file:` get invoked at all during dannce-train? Does it matter what COM file gets listed here during dannce-train? Is there a way or a reason to list more than a single COM file here?

2) Could you confirm whether or not the purpose of the top-level `com_file:` is to allow specification of the COMs around which the DANNCE predictions are nucleated?

3) Is there a way to run dannce-predict on two animals simultaneously if COM files for both animals are somehow simultaneously presented under the top-level `com_file:`?

4) Is DANNCE able to spit out probabilistic predictions rather than just the best prediction for each body part?

As had been predicted and expected, the DANNCE network seems to do fine when predicting the skeletons of spatially separated animals, but gets more confused (including with COMs) when two animals are close together. We will plan to troubleshoot COM accuracy by training on more COM labels from frames in which animals are close together and by improving COM prediction post-processing, but would also like to better understand how COM files are used in io.yaml in general.

Many, many thanks again,
Shuyu

```
### COM ###
# path to folder where COM weights and logs will be saved
com_train_dir: D:\6camera-trials\exp-rgb_cal_test_clone\COM\train_results\
com_predict_dir: D:\6camera-trials\exp-rgb_cal_test_clone\COM\predict_results\

com_exp:
  - label3d_file: D:\6camera-trials\exp-rgb_cal_test_clone\20220420_101636_Label3D_dannce.mat
    camnames: ['Camera1','Camera2','Camera3','Camera4','Camera5','Camera6']

# During prediction, will look for the last epoch weights saved to ./COM/train_results/. To load in a different weights file, add the path here
# com_predict_weights: D:/videos/e12_clone/COM/train_results/weights.87-0.00021.hdf5

### Dannce ###
# path to folder where DANNCE weights and logs will be saved
dannce_train_dir: D:\6camera-trials\exp-rgb_cal_test_clone\DANNCE\2022-06-06-train_onepasstraining_splitlabels_results\AVG\
dannce_predict_dir: D:\6camera-trials\exp-rgb_cal_test_clone\DANNCE\2022-06-06-predict_onepasstraining_splitlabels_results\
dannce_predict_model: D:\6camera-trials\exp-rgb_cal_test_clone\DANNCE\2022-06-06-train_onepasstraining_splitlabels_results\AVG\fullmodel_weights\fullmodel_end.hdf5

exp:
  - label3d_file: D:\6camera-trials\exp-rgb_cal_test_clone\dannce_vole1.mat
    camnames: ['Camera1','Camera2','Camera3','Camera4','Camera5','Camera6']
    com_file: D:\6camera-trials\exp-rgb_cal_test_clone\com_vole1.mat
  - label3d_file: D:\6camera-trials\exp-rgb_cal_test_clone\dannce_vole2.mat
    camnames: ['Camera1','Camera2','Camera3','Camera4','Camera5','Camera6']
    com_file: D:\6camera-trials\exp-rgb_cal_test_clone\com_vole2.mat

#com_file: D:\6camera-trials\exp-rgb_cal_test_clone\COM\predict_results\com3d.mat # needed for DANNCE
com_file: D:\6camera-trials\exp-rgb_cal_test_clone\com_vole1.mat
```
